### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hidetnk123** [Hidetnk123/furima_28848#11]
#URL
https://furima-28848.herokuapp.com/
#Basic認証
ID : knowledge    パスワード : 24680
#出品者用のメールアドレスとパスワード
e-mail : testtest@test.com   パスワード : test1234
#購入者用のメールアドレスとパスワード
e-mail : sample@sample.com   パスワード : sample1234
#購入用カードの番号・期限・セキュリティコード
カード : 4242424242424242
期限 : 3 / 23
セキュリティコード : 123

**Comment by rumaruma0408** [comment]
Hidetnk123 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
